# AuroraKeystrokes configuration.

[hud]
    # Enables the display of the hud.
    enable = true
    # X position of the hud.
    x = 2.0
    # Y position of the hud.
    y = 2.0
    # The padding of the key boxes.
    padding = 4
    # Show the movement boxes.
    show_movement_boxes = true
    # Show the attack box.
    show_attack_box = true
    # Show the use box.
    show_use_box = true
    # Show the sneak box.
    show_sneak_box = true
    # Show the jump box.
    show_jump_box = true
    # The text display mode, available values: ACTION_NAME and KEY_NAME.
    text_display_mode = "action_name"

# CPS settings.
[cps]
    # Show CPS counter.
    show = true
    # Attach the CPS counter to the box.
    attached = true

# Colors
[colors]
    normal = "#ffffffff"
    pressed = "#ffa000ff"
    background_normal = "#000000aa"
    background_pressed = "#555555aa"
    # Enable rainbow text.
    rainbow = false
    rainbow_saturation = 0.8
