# FabricKeystrokes configuration.

[hud]
# Enables the display of the hud.
enable = true
# X position of the hud.
x = 10.0
# Y position of the hud.
y = 10.0
# The padding of the key boxes.
padding = 4
# Show the movement boxes.
show_movement_boxes = true
# Show the attack and interact buttons boxes.
show_interaction_boxes = true
# Show the sneak box.
show_sneak_box = true
# Show the jump box.
show_jump_box = true
# The text display mode, available values: ACTION_NAME and KEY_NAME.
text_display_mode = "action_name"

# CPS settings.
[cps]
# Show CPS counter.
show = true
# Attach the CPS counter to the box.
attached = true

# Colors
[colors]
normal = "#FFFFFFFF"
pressed = "#FFA000FF"
background_normal = "#000000AA"
background_pressed = "#555555AA"
